商品添加南北校、出售或求购、联系方式
SCUT-StudentUnion/Market-backend pull request #15
Opened 2018-11-27 09:40 UTC by Ellllll

2018-12-16 16:10 UTC, huww98 requested changes
不错，现在我们需要写一下db/changelog了，@Ellllll 你有兴趣研究下吗？还是直接我来写？

2018-12-16 16:10 UTC, huww98 commented on src/main/java/org/scutsu/market/models/Goods.java
> -	private BigDecimal buyingPrice;
这里是上次讨论的时候说不要了吗？我记得好像是改成可选的或者是可以让用户随便输入点啥？

2018-12-16 16:33 UTC, Ellllll commented on src/main/java/org/scutsu/market/models/Goods.java
> -	private BigDecimal buyingPrice;
我有时间，我来写吧。售价干脆改成字符串形式的文本吧。

2019-02-02 08:07 UTC, huww98 approved these changes

2019-02-02 08:08 UTC, merged